import java.util.*;

public class TechnoHacks_EduTech_Task_2 
{
    public static void main(String args[])
    {
        Scanner sc = new Scanner(System.in);

        System.out.println("");

        System.out.println("---------------N U M B E R   G A M E---------------");
        
        System.out.println("Enter the number of attempts: ");//To store the maximum number of attempts of the user.
        int limit = sc.nextInt();

        //To store the score of the user.
        int score = 0;

        //A random number will be generated by the computer.
        int random = (int)((Math.random() * 100 ) + 1);

        for(int i = 1; i <= limit; i++)
        {
            System.out.println("Round No. " + i);
   
            //User guesses the number.
            System.out.println("Enter a guess number: ");
            int n = sc.nextInt();

            if(n == random)
            {
                System.out.println("The random number guessed by the user is correct...");
                System.out.println("Score of the user is: " + score);//Score of the user gets displayed as soon as the first condition is true.
                System.exit(0);//Program gets terminated.
            }
            else if(random > n)
            {
                System.out.println("The random number entered by the user is too low than the random number formed...");
                score += 1;
                if(limit > i)
                {
                    System.out.println("Let's move to the next round...");
                }
                continue;//Moves to the next round.
            }
            else if(random < n)
            {
                System.out.println("The random number entered by the user is too high than the random number formed...");
                score += 1;
                if(limit > i)
                {
                    System.out.println("Let's move to the next round...");
                }
                continue;//Moves to the next round.
            }
        }
        sc.close();//Closing of Scanner class.
    }    
}
